{{- if .Values.serviceAccount.clusterRbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kannika-api.name" . }}
  labels:
{{ include "kannika-api.labels" . | indent 4 }}
rules:
{{ include "kannika-api.rules" (list $ "resource-manager") | indent 2 }}
{{- end }}
