{{- if .Values.serviceAccount.create }}
{{- if .Values.serviceAccount.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kannika-api.name" . }}:resource-manager
  namespace: {{ include "kannika-api.kubernetesNamespace" . }}
  labels:
{{ include "kannika-api.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kannika-api.name" . }}:resource-manager
subjects:
  - kind: ServiceAccount
    name: {{ include "kannika-api.serviceAccount" . }}
    namespace: {{.Release.Namespace }}
{{- end }}
{{- end }}
