name: Merge Chart Values

on:
  workflow_dispatch:
  schedule:
    # Run weekly to catch value changes
    - cron: "0 0 * * 0"
  push:
    paths:
      - "charts/armory/kannika/values.yaml"
      - "charts/armory/kannika-api/values.yaml"
      - "charts/armory/kannika-console/values.yaml"
      - "charts/armory/kannika-operator/values.yaml"
      - "scripts/merge-values.sh"
      - ".github/workflows/merge-values.yaml"

jobs:
  merge-values:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to push the new branch
      pull-requests: write # Required to create the actual PR
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq

      - name: Merge Armory values
        run: |
          chmod +x ./scripts/merge-values.sh
          ./scripts/merge-values.sh \
            ./charts/armory/kannika \
            ./charts/armory/kannika-api \
            ./charts/armory/kannika-console \
            ./charts/armory/kannika-operator > ./charts/armory/values.yaml

      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code charts/kannika/values.yaml || echo "changed=true" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        if: steps.git-check.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: update merged values.yaml from subcharts"
          title: "Update merged values.yaml"
          body: |
            This PR automatically updates merged values.yaml files.

            Please review the changes before merging.
          branch: auto/merge-values
          delete-branch: true
          labels: |
            automated
            helm
