{{- if .Values.serviceAccount.create }}
{{- if .Values.serviceAccount.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kannika-operator.name" . }}:license-reader
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "kannika-operator.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kannika-operator.name" . }}:license-reader
subjects:
  - kind: ServiceAccount
    name: {{ include "kannika-operator.serviceAccount" . }}
    namespace: {{.Release.Namespace }}
{{- end }}
{{- end }}
