{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kannika-operator.serviceAccount" . }}
{{- if .Values.serviceAccount.annotations }}
  annotations: {{ toYaml .Values.serviceAccount.annotations | nindent 4 }}
{{- end }}
  labels:
    {{- include "kannika-operator.labels" . | nindent 4 }}
{{- end }}
